### PR TITLE
Option of filter projections via sums

### PR DESCRIPTION
**Pull request by bd-j**
This PR implements the optional use of simple sums to do filter projections, for reasons of speed.  It requires that a `dlnlam` and `wmin` parameter be supplied at instatiation, and that the flux vector supplied to the projection algorithm be interpolated onto a wavelength grid defined by these parameters.  The optional keyword `gridded=True` is used to select this option.

There are also some smaller changes that compactify the filter transmission functions, and the out-of-date inefficient and poorly tested spectral smoothing algorithms are moved to their own module for eventual replacement by the algorithms in prospector.

In progress, as more testing of the algorithms is necessary.

### CODE REVIEW

**Comment by bd-j** [comment]
@joshspeagle, @jrleja this is most of what is necessary to address #6.  Comments and suggestions welcome.  Needs testing, and should probably raise an error if `dlnlam` doesn't adequately sample the native transmission function.  I am assuming for now that redshifting of the source spectrum will be handled exterior to sedpy during interpolation onto the appropriate grid.

**Comment by bd-j** [comment]
ok, working on testing this, fixed some critical bugs.  The following script makes sure the magnitudes aren't insane with the grids, and can be used to find timings. The gains of the gridded sum versus the interpolation and trapezoidal integration depend very sensitively on the grid spacing (the sum often has to go over a huge vector, since the minimum dlnlam to make sure you always resolve the filter can be quite small.  Though one can imagine editing the highest resolution filter curves -- I'm looking at you HST -- to be at worse resolution, which is probably fine)

here's the testing block
```
import sys
import numpy as np
from sedpy import observate
fnames = np.array(observate.list_available_filters())
obs = {}
allfilters = observate.load_filters(fnames)
w = np.array([f.wave_effective for f in allfilters])
good = w < 1e5

obs['filters'] = observate.load_filters(fnames[good][0:40])

spec = np.random.uniform(0, 1.0, 5996)
wave = np.exp(np.linspace(np.log(90), np.log(1e6), len(spec)))
#%timeit m = observate.getSED(wave, spec, obs['filters'])
#3.22 ms
m_default = observate.getSED(wave, spec, obs['filters'])

wlo, whi, dlo = [], [], []
for f in obs['filters']:
    dlnlam = np.gradient(f.wavelength)/f.wavelength
    wlo.append(f.wavelength.min())
    dlo.append(dlnlam.min())
    whi.append(f.wavelength.max())
wmin = np.min(wlo)
wmax = np.max(whi)
dlnlam = np.min(dlo)
obs['filters'] = observate.load_filters(fnames[good][0:40],
                                        dlnlam=dlnlam, wmin=wmin)

lnlam = np.exp(np.arange(np.log(wmin), np.log(wmax), dlnlam))
lnspec = np.interp(lnlam, wave, spec)

#%timeit m = observate.getSED(lnlam, lnspec, obs['filters'], gridded=True)
# 3.7ms
m_grid = m = observate.getSED(lnlam, lnspec, obs['filters'], gridded=True)

for f, d, delt in zip(obs['filters'], dlo, m_grid - m_default):
    print('{:25s}: {:8.5f} {:7.5f}'.format(f.name, delt, d))
```

**Comment by jrleja** [comment]
assuming you do use unedited HST filters (i.e. the worst case), what is the gain over the previous implementation?

**Comment by bd-j** [comment]
nil.  it's actually a little worse than the old case

**Comment by jrleja** [comment]
ew. so to really get gains from this, we'd need a higher minimum resolution. is it crazy to imagine adding a rebin_transmission_curve method to filter objects in sedpy, which rebins the transmission curve to some minimum resolution (e.g. the minimum library resolution?).

this could be taken care of in load_obs() so the original filter files remain untouched.

**Comment by bd-j** [comment]
sorry, scratch the above.  for acs_f814 the minimum dlnlam is 3e-5.  Using this with the first 40 filters with effective wavelengths < 10 micron yields a getSED timing of 2.7 milliseconds, vs 4milliseconds for the old implementation.  The timing scales as 1/sqrt(dlnlam), so upping dlnlam to 3e-4 gives ~0.8 milliseconds for the same 40 filters.

**Comment by bd-j** [comment]
I'd be happy to accept a PR with a rebin_transmission method for the filter objects

**Comment by bd-j** [comment]
and actually I don't totally understand the time scaling with dlnlam, it doesn't seem to go quite as sqrt(dlnlam)

**Comment by jrleja** [comment]
I'd potentially be willing to write that method, depending on the gain. but the gain seems small-- my likelihood calls are more like 40-50 ms on an intel core. interpreting this naively, the max gain would be 2.7ms-->0ms or a ~5% speedup. which seems like basically nothing. what's dominating the likelihood call now for photometry anyway?

**Comment by bd-j** [comment]
I don't know.  This is for add_neb = false, right?

**Comment by bd-j** [comment]
anyway, I'm merging this and we can use it or not

**Pull request merged**
